USE [master]
GO

/****** Object:  Database [Login]    Script Date: 29/10/2017 5:48:17 CH ******/
CREATE DATABASE [Login]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Login', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Login.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Login_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Login_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Login] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Login].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Login] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Login] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Login] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Login] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Login] SET ARITHABORT OFF 
GO

ALTER DATABASE [Login] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Login] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Login] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Login] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Login] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Login] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Login] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Login] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Login] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Login] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Login] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Login] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Login] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Login] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Login] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Login] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Login] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Login] SET RECOVERY FULL 
GO

ALTER DATABASE [Login] SET  MULTI_USER 
GO

ALTER DATABASE [Login] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Login] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Login] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Login] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Login] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Login] SET  READ_WRITE 
GO

